package kz.osu.cinimex.lifecycle;

public enum State {
    REQUESTED_BY_USER, REQUEST_SENT_TO_CFT, CHECKS_STARTED, OPENED,
    CHECKS_COMPLETED, CHECKS_FAILED, REQUEST_REJECTED, REQUEST_REJECTED_BY_CFT, BLOCKED, CLOSED
}
